import type { Metadata } from "next";
import { Urbanist } from 'next/font/google'
import "./globals.css";
import ToastContainer from "./components/ToastContainer";

const urbanist = Urbanist({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-urbanist',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"   className={`${urbanist.variable} `}>
      <body
      
      >
         <ToastContainer />
        {children}
      </body>
    </html>
  );
}
